/**
 * Aura Moods - CSS/Tailwind 輸出模組
 */

import { getTheme } from './themes.js';

/**
 * 生成動態 CSS（含 keyframes）
 * @param {string} themeId
 * @returns {string}
 */
export function generateCSS(themeId) {
  const theme = getTheme(themeId);

  return `/* ===========================================
   ${theme.name} (${theme.nameEn}) - Aura Moods
   Generated by Aura Moods 動態氛圍色票
   https://github.com/tznthou/muripo-hq
   =========================================== */

/* === HTML Structure ===
<div class="aura-background">
  <div class="blob blob-1"></div>
  <div class="blob blob-2"></div>
  <div class="blob blob-3"></div>
  <div class="blob blob-4"></div>
</div>
=== End HTML Structure === */

/* CSS Variables */
:root {
  /* Blob Colors (with RGB fallback) */
  --blob-1: ${theme.blobs[0].rgb};
  --blob-2: ${theme.blobs[1].rgb};
  --blob-3: ${theme.blobs[2].rgb};
  --blob-4: ${theme.blobs[3].rgb};
  --bg-base: ${theme.bgBase.rgb};

  /* Animation Speed (1 = normal) */
  --speed-multiplier: 1;

  /* Blur Amount */
  --blur-amount: 120px;
}

/* OKLCH colors for modern browsers */
@supports (color: oklch(0% 0 0)) {
  :root {
    --blob-1: ${theme.blobs[0].oklch};
    --blob-2: ${theme.blobs[1].oklch};
    --blob-3: ${theme.blobs[2].oklch};
    --blob-4: ${theme.blobs[3].oklch};
    --bg-base: ${theme.bgBase.oklch};
  }
}

/* Background Container */
.aura-background {
  position: fixed;
  inset: 0;
  z-index: -1;
  overflow: hidden;
  background: var(--bg-base);
}

/* Blob Base Style */
.blob {
  position: absolute;
  border-radius: 50%;
  filter: blur(var(--blur-amount));
  opacity: 0.8;
  will-change: transform;
  transform: translateZ(0);
}

/* Individual Blobs */
.blob-1 {
  width: 50vmax;
  height: 50vmax;
  background: var(--blob-1);
  top: -10%;
  left: -10%;
  animation: float-1 calc(18s / var(--speed-multiplier)) ease-in-out infinite;
}

.blob-2 {
  width: 45vmax;
  height: 45vmax;
  background: var(--blob-2);
  top: 50%;
  right: -15%;
  animation: float-2 calc(23s / var(--speed-multiplier)) ease-in-out infinite;
}

.blob-3 {
  width: 40vmax;
  height: 40vmax;
  background: var(--blob-3);
  bottom: -10%;
  left: 30%;
  animation: float-3 calc(20s / var(--speed-multiplier)) ease-in-out infinite;
}

.blob-4 {
  width: 35vmax;
  height: 35vmax;
  background: var(--blob-4);
  top: 30%;
  left: 50%;
  animation: float-4 calc(15s / var(--speed-multiplier)) ease-in-out infinite;
}

/* Organic Float Animations */
@keyframes float-1 {
  0%, 100% { transform: translate(0, 0) scale(1); }
  25% { transform: translate(15%, 20%) scale(1.05); }
  50% { transform: translate(5%, 35%) scale(0.95); }
  75% { transform: translate(-10%, 15%) scale(1.02); }
}

@keyframes float-2 {
  0%, 100% { transform: translate(0, 0) scale(1); }
  33% { transform: translate(-20%, -15%) scale(1.08); }
  66% { transform: translate(-10%, 20%) scale(0.92); }
}

@keyframes float-3 {
  0%, 100% { transform: translate(0, 0) scale(1); }
  20% { transform: translate(25%, -10%) scale(0.98); }
  40% { transform: translate(10%, -25%) scale(1.06); }
  60% { transform: translate(-15%, -15%) scale(0.94); }
  80% { transform: translate(-5%, 10%) scale(1.02); }
}

@keyframes float-4 {
  0%, 100% { transform: translate(0, 0) scale(1); }
  25% { transform: translate(-30%, 20%) scale(1.1); }
  50% { transform: translate(-15%, -20%) scale(0.9); }
  75% { transform: translate(10%, -10%) scale(1.05); }
}

/* Optional: Pause animation */
.aura-background.paused .blob {
  animation-play-state: paused;
}

/* Optional: Low performance mode */
.low-perf {
  --blur-amount: 60px;
}
.low-perf .blob:nth-child(n+3) {
  display: none;
}`;
}

/**
 * 生成靜態 CSS（無動畫）
 * @param {string} themeId
 * @returns {string}
 */
export function generateStaticCSS(themeId) {
  const theme = getTheme(themeId);

  return `/* ===========================================
   ${theme.name} (${theme.nameEn}) - Aura Moods (Static)
   Generated by Aura Moods 動態氛圍色票
   =========================================== */

/* === HTML Structure ===
<div class="aura-background">
  <div class="blob blob-1"></div>
  <div class="blob blob-2"></div>
  <div class="blob blob-3"></div>
  <div class="blob blob-4"></div>
</div>
=== End HTML Structure === */

:root {
  --blob-1: ${theme.blobs[0].rgb};
  --blob-2: ${theme.blobs[1].rgb};
  --blob-3: ${theme.blobs[2].rgb};
  --blob-4: ${theme.blobs[3].rgb};
  --bg-base: ${theme.bgBase.rgb};
  --blur-amount: 120px;
}

@supports (color: oklch(0% 0 0)) {
  :root {
    --blob-1: ${theme.blobs[0].oklch};
    --blob-2: ${theme.blobs[1].oklch};
    --blob-3: ${theme.blobs[2].oklch};
    --blob-4: ${theme.blobs[3].oklch};
    --bg-base: ${theme.bgBase.oklch};
  }
}

.aura-background {
  position: fixed;
  inset: 0;
  z-index: -1;
  overflow: hidden;
  background: var(--bg-base);
}

.blob {
  position: absolute;
  border-radius: 50%;
  filter: blur(var(--blur-amount));
  opacity: 0.8;
}

.blob-1 {
  width: 50vmax;
  height: 50vmax;
  background: var(--blob-1);
  top: -10%;
  left: -10%;
}

.blob-2 {
  width: 45vmax;
  height: 45vmax;
  background: var(--blob-2);
  top: 50%;
  right: -15%;
}

.blob-3 {
  width: 40vmax;
  height: 40vmax;
  background: var(--blob-3);
  bottom: -10%;
  left: 30%;
}

.blob-4 {
  width: 35vmax;
  height: 35vmax;
  background: var(--blob-4);
  top: 30%;
  left: 50%;
}`;
}

/**
 * 生成 Tailwind 顏色 Token
 * @param {string} themeId
 * @returns {string}
 */
export function generateTailwindTokens(themeId) {
  const theme = getTheme(themeId);

  // 從 oklch 提取值用於 Tailwind 4
  const extractOklch = (str) => str.replace('oklch(', '').replace(')', '');

  return `/* ===========================================
   ${theme.name} (${theme.nameEn}) - Tailwind Color Tokens
   Generated by Aura Moods 動態氛圍色票

   Note: Animation keyframes need to be added manually.
   These tokens work with Tailwind CSS v4 (OKLCH support).
   =========================================== */

/* Tailwind v4 - CSS Theme Variables */
@theme {
  --color-aura-bg: ${theme.bgBase.oklch};
  --color-aura-blob-1: ${theme.blobs[0].oklch};
  --color-aura-blob-2: ${theme.blobs[1].oklch};
  --color-aura-blob-3: ${theme.blobs[2].oklch};
  --color-aura-blob-4: ${theme.blobs[3].oklch};
}

/* Usage Example:
   <div class="bg-aura-bg">
     <div class="bg-aura-blob-1 blur-[120px]"></div>
   </div>
*/

/* Fallback for Tailwind v3 (tailwind.config.js) */
/*
module.exports = {
  theme: {
    extend: {
      colors: {
        'aura-bg': '${theme.bgBase.rgb}',
        'aura-blob-1': '${theme.blobs[0].rgb}',
        'aura-blob-2': '${theme.blobs[1].rgb}',
        'aura-blob-3': '${theme.blobs[2].rgb}',
        'aura-blob-4': '${theme.blobs[3].rgb}',
      }
    }
  }
}
*/`;
}

/**
 * 複製文字到剪貼簿
 * @param {string} text
 * @returns {Promise<boolean>}
 */
export async function copyToClipboard(text) {
  try {
    // 優先使用 Clipboard API
    if (navigator.clipboard && navigator.clipboard.writeText) {
      await navigator.clipboard.writeText(text);
      return true;
    }

    // Fallback: execCommand
    const textarea = document.createElement('textarea');
    textarea.value = text;
    textarea.style.position = 'fixed';
    textarea.style.left = '-9999px';
    textarea.style.top = '-9999px';
    document.body.appendChild(textarea);
    textarea.focus();
    textarea.select();

    const success = document.execCommand('copy');
    document.body.removeChild(textarea);
    return success;
  } catch (err) {
    console.error('Copy failed:', err);
    return false;
  }
}
